import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ProductDetail } from "@/components/product-detail";
import { portfolioAreasFr, productsFr } from "@/lib/content-fr";

type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return productsFr.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const product = productsFr.find((item) => item.slug === slug); return { title: product?.name ?? "Produit", description: product?.overview, robots: { index: false, follow: false } }; }

export default async function FrenchProductPage({ params }: Props) { const { slug } = await params; const product = productsFr.find((item) => item.slug === slug); if (!product) notFound(); const area = portfolioAreasFr.find((item) => item.slug === product.area)!; const related = productsFr.filter((item) => item.area === product.area && item.slug !== slug); return <><header className="product-hero"><Image src={area.image} alt={area.imageAlt} fill priority sizes="100vw" className="product-hero-image" /><div className="shell product-hero-content"><Link className="back-link" href={`/fr/portfolio#${area.slug}`}>← {area.title}</Link><p className="eyebrow">{product.category}</p><h1 className="display-title">{product.name}</h1><p>{product.overview}</p></div></header><ProductDetail product={product} labels={{ overviewEyebrow: "Aperçu du produit", overviewTitle: "De quoi s’agit-il.", howItWorks: "Fonctionnement", specsEyebrow: "Spécifications", specsTitle: "Chiffres clés.", contextEyebrow: "Information sur le portefeuille", contextTitle: "Issu du portefeuille d’origine.", badge: "Contenu à réviser", note: "Cette page conserve l’information produit de l’ancien site à des fins de révision. Elle ne confirme pas la disponibilité au Canada, les indications approuvées, les performances ni les renseignements thérapeutiques. Demandez la documentation vérifiée avant de vous y fier.", cta: "Demander l’information vérifiée", ctaSubject: "Demande d’information", legacySource: "Voir sur l’ancien site" }} />{related.length > 0 ? <section className="section section-blue"><div className="shell"><p className="eyebrow">Explorer ce domaine</p><h2 className="section-title">Produits connexes</h2><div className="related-products">{related.map((item) => <Link href={`/fr/portfolio/${item.slug}`} key={item.slug}>{item.name}<span aria-hidden="true">↗</span></Link>)}</div></div></section> : null}</>; }
