import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { portfolioAreasFr, productsFr } from "@/lib/content-fr";

type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return productsFr.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const product = productsFr.find((item) => item.slug === slug); return { title: product?.name ?? "Produit", description: product?.overview, robots: { index: false, follow: false } }; }

export default async function FrenchProductPage({ params }: Props) { const { slug } = await params; const product = productsFr.find((item) => item.slug === slug); if (!product) notFound(); const area = portfolioAreasFr.find((item) => item.slug === product.area)!; const related = productsFr.filter((item) => item.area === product.area && item.slug !== slug); return <><header className="product-hero"><Image src={area.image} alt={area.imageAlt} fill priority sizes="100vw" className="product-hero-image" /><div className="shell product-hero-content"><Link className="back-link" href={`/fr/portfolio#${area.slug}`}>← {area.title}</Link><p className="eyebrow">{product.category}</p><h1 className="display-title">{product.name}</h1><p>{product.overview}</p></div></header><section className="section shell product-detail" aria-labelledby="context-heading"><div><p className="eyebrow">Information sur le portefeuille</p><h2 className="section-title" id="context-heading">Issu du portefeuille d’origine.</h2></div><div><span className="status-badge">Contenu à réviser</span><p>{product.legacyContext}</p><p className="detail-note">Cette page conserve le contexte de l’ancien site à des fins de révision. Elle ne confirme pas la disponibilité au Canada, les indications approuvées, les performances ni les renseignements thérapeutiques.</p><a className="button-primary" href={`mailto:info@ribicongroup.com?subject=${encodeURIComponent(`Demande d’information : ${product.name}`)}`}>Demander l’information vérifiée</a></div></section>{related.length > 0 ? <section className="section section-blue"><div className="shell"><p className="eyebrow">Explorer ce domaine</p><h2 className="section-title">Produits connexes</h2><div className="related-products">{related.map((item) => <Link href={`/fr/portfolio/${item.slug}`} key={item.slug}>{item.name}<span aria-hidden="true">↗</span></Link>)}</div></div></section> : null}</>; }
