import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowLink } from "@/components/arrow-link";
import { portfolioAreasFr } from "@/lib/content-fr";

export const metadata: Metadata = { title: "Soins de santé spécialisés", description: "Ribicon Pharma est une entreprise canadienne active dans les diagnostics et les thérapies spécialisées.", alternates: { canonical: "/fr", languages: { "en-CA": "/", "fr-CA": "/fr" } } };

export default function FrenchHomePage() {
  const featured = portfolioAreasFr[0];
  return <>
    <section className="hero" aria-labelledby="hero-title"><Image className="hero-image" src="/hero-diagnostics.png" alt="Équipement de diagnostic de précision avec une goutte d’échantillon" fill priority sizes="100vw" /><div className="shell hero-content"><div className="hero-copy"><p className="eyebrow">Soins spécialisés basés au Canada</p><h1 className="display-title" id="hero-title">La précision ouvre les possibles.</h1><p>Ribicon Pharma relie diagnostics et thérapies spécialisés aux professionnels et partenaires qui font progresser les soins.</p><div className="hero-actions"><Link className="button-primary" href="/fr/portfolio">Explorer le portefeuille</Link><Link className="button-secondary" href="/fr/contact">Devenir partenaire</Link></div></div></div><p className="hero-note">Diagnostics · Médicaments spécialisés · Partenariats commerciaux</p></section>
    <section className="section" aria-labelledby="portfolio-heading"><div className="shell"><div className="section-heading-row"><div><p className="eyebrow">Portefeuille ciblé</p><h2 className="section-title" id="portfolio-heading">Se spécialiser là où cela compte.</h2></div><p>Un portefeuille volontairement ciblé en diagnostic et en soins spécialisés, organisé en domaines thérapeutiques clairs.</p></div><div className="portfolio-showcase"><article className="feature-card"><Image className="feature-image" src={featured.image} alt={featured.imageAlt} fill sizes="(max-width: 800px) 100vw, 65vw" /><div className="feature-card-content"><p className="eyebrow">{featured.number} · {featured.eyebrow}</p><h3>{featured.title}</h3><p>{featured.summary}</p><ArrowLink href={`/fr/portfolio#${featured.slug}`} inverse>Voir les diagnostics</ArrowLink></div></article><div className="area-list">{portfolioAreasFr.slice(1).map((area) => <Link className="area-row" href={`/fr/portfolio#${area.slug}`} key={area.slug}><span>{area.number}</span><span className="area-thumb"><Image src={area.image} alt="" fill sizes="88px" /></span><span><h3>{area.title}</h3><p>{area.eyebrow}</p></span><span className="arrow" aria-hidden="true">↗</span></Link>)}</div></div></div></section>
    <section className="section section-blue" aria-labelledby="story-heading"><div className="shell split-story"><div className="story-visual"><Image src="/ophthalmology-editorial.jpg" alt="Examen ophtalmologique en milieu clinique" fill sizes="(max-width: 800px) 100vw, 40vw" /><span>Des soins adaptés aux besoins spécialisés.</span></div><div className="story-copy"><p className="eyebrow">Ribicon Pharma</p><h2 className="section-title" id="story-heading">Une perspective locale. Une expérience internationale.</h2><p>Depuis notre base canadienne, nous collaborons avec un réseau de partenaires de la santé afin d’acheminer des produits spécialisés vers les marchés et professionnels concernés.</p><ArrowLink href="/fr/about">Découvrir notre approche</ArrowLink></div></div></section>
    <section className="section" aria-labelledby="difference-heading"><div className="shell"><p className="eyebrow">Notre façon de travailler</p><h2 className="section-title" id="difference-heading">Des priorités claires. Une croissance responsable.</h2><div className="proof-strip"><article className="proof-item"><span>01</span><h3>Portefeuille spécialisé</h3></article><article className="proof-item"><span>02</span><h3>Expertise commerciale et de marché</h3></article><article className="proof-item"><span>03</span><h3>Soutien axé sur les partenaires</h3></article></div></div></section>
    <section className="section section-dark" aria-labelledby="contact-heading"><div className="shell cta-panel"><div><p className="eyebrow" style={{ color: "#aee9f8" }}>Entamer une conversation</p><h2 className="section-title" id="contact-heading">Construisons l’avenir des soins spécialisés.</h2></div><div><p>Pour les partenariats commerciaux, les demandes liées au portefeuille ou l’information d’entreprise.</p><ArrowLink href="/fr/contact" inverse>Contacter Ribicon Pharma</ArrowLink></div></div></section>
  </>;
}
