import type { Metadata } from "next";
import { PageHero } from "@/components/page-hero";
import Image from "next/image";
import Link from "next/link";
import { portfolioAreasFr, productsFr } from "@/lib/content-fr";

export const metadata: Metadata = { title: "Portefeuille", description: "Découvrez le portefeuille de Ribicon Pharma en diagnostic, thérapies spécialisées, ophtalmologie et cardiologie." };

export default function FrenchPortfolioPage() { return <><PageHero image="/hero-diagnostics.png"><p className="eyebrow">Notre portefeuille</p><h1 className="display-title">Ciblé par choix.</h1><p>Une vue claire des domaines d’intérêt actuels de Ribicon Pharma. Les renseignements détaillés ne sont publiés qu’après une révision médicale et réglementaire appropriée.</p></PageHero><div className="shell portfolio-stack">{portfolioAreasFr.map((area) => <section className="portfolio-section" id={area.slug} key={area.slug}><span className="portfolio-number">{area.number}</span><div className="portfolio-title"><div className="portfolio-visual"><Image src={area.image} alt={area.imageAlt} fill sizes="(max-width: 800px) 100vw, 450px" /></div><p className="eyebrow">{area.eyebrow}</p><h2>{area.title}</h2><p>{area.summary}</p>{area.status === "draft" ? <span className="status-badge">Information à venir</span> : null}</div>{area.products.length > 0 ? <ul className="product-list" aria-label={`Produits — ${area.title}`}>{area.products.map((name) => { const product = productsFr.find((item) => item.name === name); return <li key={name}>{product ? <Link href={`/fr/portfolio/${product.slug}`}>{name}<span aria-hidden="true">↗</span></Link> : name}</li>; })}</ul> : <p>Les noms de produits, usages prévus, espèces et documents justificatifs seront ajoutés après confirmation du portefeuille.</p>}</section>)}</div><section className="section section-blue"><div className="shell content-grid"><div><p className="eyebrow">Pour les professionnels de la santé</p><h2>Besoin d’information vérifiée?</h2></div><div><p>Communiquez avec Ribicon Pharma pour connaître le statut actuel des produits, obtenir la documentation canadienne approuvée et demander de l’information médicale.</p><a className="button-primary" href="mailto:info@ribicongroup.com?subject=Demande%20d%27information%20sur%20un%20produit">Demander de l’information</a></div></div></section></>; }
