import type { PortfolioArea, Product } from "@/lib/content";

export const portfolioAreasFr: PortfolioArea[] = [
  { slug: "solid-tumor-biomarkers", number: "01", title: "Biomarqueurs de tumeurs solides", eyebrow: "Diagnostic", summary: "Un portefeuille ciblé de biomarqueurs associés à l’évaluation et au suivi des tumeurs solides.", products: ["Alpha-fœtoprotéine (AFP)", "CA-125", "Carcinome gastrique GC-REAAD", "Carcinome hépatocellulaire HCC-REAAD", "Carcinome nasopharyngé NPC-REAAD"], image: "/hero-diagnostics.png", imageAlt: "Équipement de diagnostic en laboratoire et goutte d’échantillon" },
  { slug: "targeted-therapeutics", number: "02", title: "Thérapies ciblées", eyebrow: "Médicaments spécialisés", summary: "Des thérapies spécialisées destinées aux professionnels de la santé et aux établissements.", products: ["Tepadina (thiotépa)", "Phelinun (melphalan)"], image: "/therapeutics-editorial.jpg", imageAlt: "Professionnel de la santé préparant un flacon en laboratoire clinique" },
  { slug: "ophthalmology", number: "03", title: "Ophtalmologie", eyebrow: "Santé oculaire", summary: "Un portefeuille ophtalmologique concis pour la prise en charge de la pression intraoculaire.", products: ["Gouttes ophtalmiques de bimatoprost", "Gouttes ophtalmiques de latanoprost"], image: "/ophthalmology-editorial.jpg", imageAlt: "Patiente lors d’un examen ophtalmologique" },
  { slug: "cardiology", number: "04", title: "Cardiologie", eyebrow: "Diagnostic cardiaque", summary: "Des outils et tests diagnostiques pour soutenir l’évaluation cardiovasculaire.", products: ["ECG Vectraplex", "Test de troponine"], image: "/cardiology-signal.svg", imageAlt: "Illustration d’un signal électrocardiographique" },
  { slug: "veterinary-diagnostics", number: "05", title: "Diagnostics vétérinaires", eyebrow: "Portefeuille en développement", summary: "Un futur portefeuille de biomarqueurs diagnostiques. Les renseignements seront publiés après révision.", products: [], image: "/hero-diagnostics.png", imageAlt: "Équipement de laboratoire représentant les futurs diagnostics vétérinaires", status: "draft" },
];

export const productsFr: Product[] = [
  { slug: "afp", name: "Alpha-fœtoprotéine (AFP)", area: "solid-tumor-biomarkers", category: "Biomarqueur de tumeur solide", overview: "Un biomarqueur de laboratoire associé à l’évaluation et au suivi dans certains contextes de tumeurs solides.", legacyContext: "L’ancien site présente l’AFP dans le contexte des cancers du foie, de l’ovaire et du testicule, en précisant que le résultat doit être interprété avec les autres données cliniques.", legacyUrl: "https://ribicongroup.com/products/biomarkers/alpha-fetoprotein-afp/" },
  { slug: "ca-125", name: "CA-125", area: "solid-tumor-biomarkers", category: "Biomarqueur de tumeur solide", overview: "Un biomarqueur utilisé dans l’évaluation clinique et le suivi du cancer de l’ovaire.", legacyContext: "L’ancien site décrit le CA-125 dans le suivi de la réponse au traitement et de la récidive; il ne constitue pas à lui seul un diagnostic.", legacyUrl: "https://ribicongroup.com/products/biomarkers/ca-125/" },
  { slug: "gc-reaad", name: "Carcinome gastrique GC-REAAD", area: "solid-tumor-biomarkers", category: "Biomarqueur de tumeur solide", overview: "Une offre diagnostique associée au carcinome gastrique sur l’ancien site.", legacyContext: "La description historique mentionne un dosage ELISA ITIH3 sur plasma humain. La disponibilité, la validation et l’usage prévu doivent être confirmés.", legacyUrl: "https://ribicongroup.com/products/biomarkers/gastric-carcinoma-gc-reaad/" },
  { slug: "hcc-reaad", name: "Carcinome hépatocellulaire HCC-REAAD", area: "solid-tumor-biomarkers", category: "Biomarqueur de tumeur solide", overview: "Une offre de biomarqueur diagnostique associée au carcinome hépatocellulaire.", legacyContext: "La description historique mentionne un dosage ELISA ERBB3 et un algorithme intégrant l’AFP. L’usage prévu précis doit être vérifié.", legacyUrl: "https://ribicongroup.com/products/biomarkers/hepatocellular-carcinoma-hcc-reaad/" },
  { slug: "npc-reaad", name: "Carcinome nasopharyngé NPC-REAAD", area: "solid-tumor-biomarkers", category: "Biomarqueur de tumeur solide", overview: "Une offre de biomarqueur diagnostique associée au carcinome nasopharyngé.", legacyContext: "La description historique mentionne un dosage ELISA EBV EA-IgA sur sérum ou plasma. Les spécifications actuelles doivent être confirmées.", legacyUrl: "https://ribicongroup.com/products/biomarkers/nasopharyngeal-carcinoma-npc-reaad/" },
  { slug: "tepadina", name: "Tepadina (thiotépa)", area: "targeted-therapeutics", category: "Thérapie spécialisée", overview: "Un médicament spécialisé à base de thiotépa figurant dans l’ancien portefeuille thérapeutique de Ribicon.", legacyContext: "L’ancien site évoque son utilisation dans le conditionnement avant une greffe de cellules souches et dans certains contextes oncologiques. L’autorisation locale et les indications approuvées doivent être vérifiées.", legacyUrl: "https://ribicongroup.com/products/targeted-therapeutics/tepadina/" },
  { slug: "phelinun", name: "Phelinun (melphalan)", area: "targeted-therapeutics", category: "Thérapie spécialisée", overview: "Un médicament spécialisé à base de melphalan figurant dans l’ancien portefeuille thérapeutique.", legacyContext: "L’ancien site décrit des utilisations en oncologie et en transplantation. La disponibilité, l’étiquetage et les indications au Canada doivent être confirmés.", legacyUrl: "https://ribicongroup.com/products/targeted-therapeutics/phelinun/" },
  { slug: "bimatoprost", name: "Gouttes ophtalmiques de bimatoprost", area: "ophthalmology", category: "Ophtalmologie", overview: "Des gouttes ophtalmiques analogues des prostaglandines incluses dans l’ancien portefeuille.", legacyContext: "L’ancien site présente le bimatoprost pour la prise en charge de la pression intraoculaire élevée et du glaucome. La formulation et l’autorisation du produit doivent être confirmées.", legacyUrl: "https://ribicongroup.com/products/ophthalmology/bimatoprost/" },
  { slug: "latanoprost", name: "Gouttes ophtalmiques de latanoprost", area: "ophthalmology", category: "Ophtalmologie", overview: "Des gouttes ophtalmiques analogues des prostaglandines incluses dans l’ancien portefeuille.", legacyContext: "L’ancien site présente le latanoprost pour la prise en charge de la pression intraoculaire élevée et du glaucome. La formulation et l’autorisation du produit doivent être confirmées.", legacyUrl: "https://ribicongroup.com/products/ophthalmology/latanoprost/" },
  { slug: "vectraplex", name: "ECG Vectraplex", area: "cardiology", category: "Cardiologie / dispositif médical", overview: "Un système d’électrocardiographie conservé de l’ancien portefeuille de cardiologie et de dispositifs médicaux.", legacyContext: "L’ancien site décrit une configuration à cinq électrodes produisant des données ECG multicanaux. Les performances techniques et l’autorisation du dispositif doivent être révisées.", legacyUrl: "https://ribicongroup.com/products/medical-devices/vectraplex/" },
  { slug: "troponin", name: "Test de troponine", area: "cardiology", category: "Biomarqueur cardiaque", overview: "Un test de biomarqueur cardiaque inclus dans l’ancien portefeuille de Ribicon.", legacyContext: "L’ancien site présente la troponine comme marqueur utilisé dans l’évaluation d’une atteinte du muscle cardiaque. Le dosage et le produit exacts restent à confirmer.", legacyUrl: "https://ribicongroup.com/products/cardiology/troponin/" },
];
